const api = {
	domain: import.meta.env.VITE_API_BASE_URL || '',
	emailCode: '/account/emailCode',
	register: '/account/register',
	login: '/account/login',
	logout: '/account/logout',
	autoLogin: '/account/autoLogin',
	changePassword: '/account/changePassword',
	getUserInfo: '/user/getUserInfo',
	updateUserInfo: '/user/updateUserInfo',
	resource: '/user/resource',
	getUserStats: '/user/getUserStats',
	recommendPapers: '/user/recommendPapers',
	sign: '/user/sign',
	getMonthSignInfo: '/user/getMonthSignInfo',
	getRecentWrongQuestions: '/wrong/getRecentWrongQuestions',
	getWrongQuestions: '/wrong/getWrongQuestions',
	getWrongQuestionById: '/wrong/getWrongQuestionById',
	addWrongQuestion: '/wrong/addWrongQuestion',
	removeWrongQuestion: '/wrong/removeWrongQuestion',
	getCategoryList: '/category/getList',
	getHotPapers: '/category/getHotPapers',
	getHotQuestions: '/category/getHotQuestions',
	getPapers: '/category/getPapers',
	search: '/question/search',
	getQuestionDetail: '/question/getQuestionDetail',
	getPaperInfo: '/paper/getPaperInfo',
	authPaper: '/paper/authPaper',
	unlockPaper: '/paper/unlockPaper',
	getRecentExam: '/exam/getRecentExam',
	getExamRecord: '/exam/getExamRecord',
	getRecordDetail: '/exam/getRecordDetail',
	getExamQuestions: '/exam/getExamQuestions',
	submitExam: '/exam/submitExam',
	uploadAndParse: '/agent/uploadAndParse',
	getTaskResult: '/agent/task'
}

export default api